# Generated by Django 2.0 on 2017-12-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientSearch', '0003_query_query_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataresource',
            name='resource_name',
            field=models.FileField(max_length=15, upload_to=''),
        ),
    ]
